### ISSUE TITLE
Por favor, cite as fontes.

### ISSUE THREAD

**Issue by Guedesou** [engenheiracoelho/GitHub#2]
Seria muito bom se você colocasse ao menos a menção de onde pegou. Pois sabemos que como o GitHub não divulga como ou quais estão disponíveis, você buscou essa info. em outro repositório. Isso é plágio. (Olha o kibee!) Por favor, cite as fontes e ajude a valorizar o trabalho de outros, e a cooperação entre devs. Não seja uma leecher aproveitadora.
![EfvVgguWAAEvRv4](https://user-images.githubusercontent.com/56264781/189135226-69efcb9e-77c7-4ca1-bd06-2d5d5fb9261e.jpg)

**Comment by engenheiracoelho** [comment]
Como indicado em todos os posts, o conteúdo e respectivas fontes estão aqui: https://github.com/engenheiracoelho/GitHub/blob/master/Medalhas_GitHub.md

Agora, por gentileza, não me importuna mais e me deixa fazer o meu trabalho
